#!/usr/bin/env node
/**
 * Converts a component's .json data file to a Drupal SDC-compatible
 * component.yml file.
 *
 * Usage: node scripts/json-to-yml.js src/components/<name>/<name>.json
 */

const fs   = require('fs');
const path = require('path');

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node scripts/json-to-yml.js <path-to-component.json>');
  process.exit(1);
}

const absInput = path.resolve(inputPath);
const dir      = path.dirname(absInput);
const name     = path.basename(dir);

let data;
try {
  data = JSON.parse(fs.readFileSync(absInput, 'utf8'));
} catch (e) {
  console.error(`Could not read/parse ${absInput}:`, e.message);
  process.exit(1);
}

const defaults = data.default || {};

/** Simple JS-value → YAML scalar */
const toYamlValue = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return String(v);
  if (typeof v === 'number')  return String(v);
  if (typeof v === 'string')  return v.includes('\n') ? `|\\n  ${v.replace(/\n/g, '\n  ')}` : `'${v.replace(/'/g, "''")}'`;
  if (Array.isArray(v))  return v.length ? `\n${v.map(i => `    - ${toYamlValue(i)}`).join('\n')}` : '[]';
  if (typeof v === 'object') return JSON.stringify(v); // nested objects — keep as JSON scalar for SDC
  return String(v);
};

const propsYaml = Object.entries(defaults)
  .map(([key, val]) => {
    const type = Array.isArray(val) ? 'array' : typeof val === 'object' && val !== null ? 'object' : typeof val;
    return `  ${key}:\n    type: ${type}\n    title: '${key}'\n    default: ${toYamlValue(val)}`;
  })
  .join('\n');

const yml = `# Auto-generated by scripts/json-to-yml.js — edit with care.
$schema: 'https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/assets/schemas/v1/metadata.schema.json'
name: '${name}'
status: stable
props:
${propsYaml}
`;

const outputPath = path.join(dir, `${name}.component.yml`);
fs.writeFileSync(outputPath, yml, 'utf8');
console.log(`Written: ${outputPath}`);
